services:
  app:
    build: .
    restart: unless-stopped
    container_name: heroncs-sync
    env_file:
      - compose.env
    # Host port (left side) can be changed without editing Dockerfile
    ports:
      - "8080:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
