services:
  app:
    image: ghcr.io/CappyTech/hcs-sync:latest
    pull_policy: always   # remove if your compose version doesn't support
    restart: unless-stopped
    container_name: hcs-sync
    env_file:
      - compose.env
    ports:
      - "8080:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
